"""
Generate test fixtures for the Shambhala_containerized test suite.

Run once from the Shambhala_containerized/ directory before executing tests:
    python tests/generate_fixtures.py

All fixture files use the FL data convention (rows = samples, columns = genes).
Source files from Shambhala2/ use the Shambhala2 internal convention
(rows = genes, columns = samples) and are transposed here.

expected_output.csv is generated by running the containerized pipeline with
--random-seed 42 --n-workers 1, making it a determinism regression fixture
rather than a cross-implementation comparison fixture.
"""

import pathlib
import sys

import numpy as np
import pandas as pd

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT.parent / "Shambhala2"
FIXTURES_DIR = REPO_ROOT / "tests" / "fixtures"
OCTAVE_DIR = REPO_ROOT / "octave"


def load_shambhala2_csv(path: pathlib.Path, skip_sample_type: bool = False) -> pd.DataFrame:
    """
    Load a Shambhala2-convention CSV (rows = genes, columns = samples).

    Parameters
    ----------
    path : pathlib.Path
        Path to the CSV file. First column must be gene symbols (used as index).
    skip_sample_type : bool
        If True, drop the 'Sample_type' metadata row before returning.

    Returns
    -------
    pd.DataFrame
        Shape: (n_genes, n_samples). Index = gene symbols. Columns = sample IDs.
        All values are float64.
    """
    df = pd.read_csv(path, index_col=0, low_memory=False)
    if skip_sample_type and "Sample_type" in df.index:
        df = df.drop(index="Sample_type")
    return df.astype(float)


def to_fl_convention(df: pd.DataFrame) -> pd.DataFrame:
    """
    Transpose a genes × samples DataFrame to samples × genes (FL convention).

    Parameters
    ----------
    df : pd.DataFrame
        Shape: (n_genes, n_samples). Index = gene symbols.

    Returns
    -------
    pd.DataFrame
        Shape: (n_samples, n_genes). Index = sample IDs.
    """
    return df.T


def main() -> None:
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)

    # input_10samples.csv — toy 10-sample input in FL convention
    print("Generating input_10samples.csv ...")
    input_genes_x_samples = load_shambhala2_csv(SRC_DIR / "Input.csv")
    input_fl = to_fl_convention(input_genes_x_samples)
    input_fl.to_csv(FIXTURES_DIR / "input_10samples.csv")
    print(f"  Shape: {input_fl.shape} (samples × genes)")

    # expected_output.csv — determinism regression reference generated by our pipeline
    # Run with random_seed=42 and n_workers=1 so results are reproducible across runs.
    # This is NOT a comparison to the original R pipeline (which used no fixed seed).
    print("Generating expected_output.csv ...")
    sys.path.insert(0, str(REPO_ROOT))
    from shambhala import io_utils, na_handling, q_rescale, parallel as parallel_module

    p_df_for_ref = to_fl_convention(
        load_shambhala2_csv(SRC_DIR / "P0.csv", skip_sample_type=True)
    ).astype(float)
    q_df_for_ref = to_fl_convention(
        load_shambhala2_csv(SRC_DIR / "Q0.csv", skip_sample_type=True)
    ).astype(float)

    input_T = input_fl.T
    p_T = p_df_for_ref.T
    q_T = q_df_for_ref.T
    common_genes = input_T.index.intersection(p_T.index).intersection(q_T.index)
    input_T = input_T.loc[common_genes]
    p_T = p_T.loc[common_genes]
    q_T = q_T.loc[common_genes]

    clean_df, na_mask = na_handling.apply_na_strategy(input_T.T, strategy="drop")
    clean_T = clean_df.T
    p_T = p_T.loc[clean_T.index]
    q_df_filtered = q_T.loc[clean_T.index].T
    rm, rs = q_rescale.compute_q_statistics(q_df_filtered)
    harmonized_T = parallel_module.harmonize_parallel(
        input_df=clean_T,
        p_df=p_T,
        rm=rm,
        rs=rs,
        k=5,
        n_workers=1,
        octave_scripts_dir=str(OCTAVE_DIR),
        octave_bin="octave",
        random_seed=42,
    )
    expected_output = na_handling.restore_na_genes(harmonized_T.T, na_mask)
    expected_output.to_csv(FIXTURES_DIR / "expected_output.csv")
    print(f"  Shape: {expected_output.shape} (samples × genes)")

    # P0_small.csv — calibration reference in FL convention
    print("Generating P0_small.csv ...")
    p_genes_x_samples = load_shambhala2_csv(SRC_DIR / "P0.csv", skip_sample_type=True)
    p_fl = to_fl_convention(p_genes_x_samples)
    p_fl.to_csv(FIXTURES_DIR / "P0_small.csv")
    print(f"  Shape: {p_fl.shape} (samples × genes)")

    # Q0_small.csv — definitive reference in FL convention
    print("Generating Q0_small.csv ...")
    q_genes_x_samples = load_shambhala2_csv(SRC_DIR / "Q0.csv", skip_sample_type=True)
    q_fl = to_fl_convention(q_genes_x_samples)
    q_fl.to_csv(FIXTURES_DIR / "Q0_small.csv")
    print(f"  Shape: {q_fl.shape} (samples × genes)")

    # input_with_nas.csv — 5% of values replaced by NaN for NA-handling tests
    print("Generating input_with_nas.csv ...")
    rng = np.random.default_rng(42)
    input_with_nas = input_fl.copy()
    n_rows, n_cols = input_with_nas.shape
    na_mask_flat = rng.random(n_rows * n_cols) < 0.05
    na_mask = na_mask_flat.reshape(n_rows, n_cols)
    input_values = input_with_nas.values.copy()
    input_values[na_mask] = np.nan
    input_with_nas = pd.DataFrame(
        input_values,
        index=input_with_nas.index,
        columns=input_with_nas.columns,
    )
    input_with_nas.to_csv(FIXTURES_DIR / "input_with_nas.csv")
    na_count = int(na_mask.sum())
    print(f"  Shape: {input_with_nas.shape} (samples × genes), NaN count: {na_count}")

    print("\nAll fixtures generated successfully.")
    for f in sorted(FIXTURES_DIR.iterdir()):
        print(f"  {f.name}")


if __name__ == "__main__":
    main()
